config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :notices
  root 'notices#index'

  devise_for :users

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :notices
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notices
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @category = Category.find(params[:id])
    @notices = @category.notices.order(created_at: :desc)
  end

  def new
  end

  def edit
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @notices = Notice.order(created_at: :desc)
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = current_user.notices.build(notice_params)

    if @notice.save
      flash[:success] = 'Your notice has been created successfully'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update

  end

  def destroy

  end

  private

  def notice_params
    params.require(:notice).permit(:category_id, :title, :description, :contacts)
  end

  def correct_user
    @notice = Notice.find(params[:id])
    unless @notice.user == current_user
      flash[:danger] = 'This is not your notice.'
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= render 'shared/notices' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Notice Board', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text">Hello, <%= current_user.name %></li>
          <li><%= link_to 'Create notice', new_notice_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoticeBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>" role="alert"><%= message %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/notices/edit.html.erb
<h1>Notices#edit</h1>
<p>Find me in app/views/notices/edit.html.erb</p>

app/views/notices/index.html.erb
<h1>All notices</h1>

<%= render 'shared/notices' %>

app/views/notices/new.html.erb
<h1>Create notice</h1>

<%= form_for @notice do |f| %>

  <div class="form-group">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :contacts %><br />
    <%= f.text_field :contacts, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/notices/show.html.erb
<%= link_to 'List of all notices', root_path %> > <%= @notice.title %>

<h1><%= @notice.title %></h1>

<p>
  Category: <%= link_to @notice.category.name, category_path(@notice.category) %>, by: <%= @notice.user.name %>
</p>

<p>
  <b>Details:</b><br />
  <%= @notice.description %>
</p>

<p>
  <b>Contacts:</b><br />
  <%= @notice.contacts %>
</p>

<p>
  <% if current_user == @notice.user %>
    <%= link_to 'Edit notice', edit_notice_path, class: 'btn btn-primary' %>
    <%= link_to 'Delete notice', notice_path(@notice), method: :delete, class: 'btn btn-danger' %>
  <% end %>
</p>

app/views/shared/_notices.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li><%= link_to 'All notices', root_path %></li>
          <% Category.all.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-8">

    <% @notices.each do |notice| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <p>Category: <%= link_to notice.category.name, category_path(notice.category) %></p>
          <h4><%= link_to notice.title, notice_path(notice) %></h4>
          <p>by: <%= notice.user.name %></p>
        </div>
      </div>
    <% end %>

  </div>
</div>